// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_PetShop.Context;

namespace Sistema_PetShop.Migrations
{
    [DbContext(typeof(AplicacaoDbContext))]
    [Migration("20201125192049_Add_Model_Usuario")]
    partial class Add_Model_Usuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sistema_PetShop.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasMaxLength(200);

                    b.Property<string>("ImagemCategoria");

                    b.Property<string>("Nome")
                        .HasMaxLength(100);

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TelFixo")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("TelMovel1")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("TelMovel2");

                    b.Property<string>("Uf")
                        .HasMaxLength(30);

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.IntercPagamentoPedido", b =>
                {
                    b.Property<int>("NumeroPedido");

                    b.Property<DateTime>("DataVenda");

                    b.Property<int>("TipoPagamentoId");

                    b.Property<string>("NumeroTransacao");

                    b.Property<decimal>("ValorPago");

                    b.HasKey("NumeroPedido", "DataVenda", "TipoPagamentoId");

                    b.HasAlternateKey("DataVenda", "NumeroPedido", "TipoPagamentoId");

                    b.HasIndex("TipoPagamentoId");

                    b.ToTable("Pagamentos_Pedidos");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.IntercProdutoPedido", b =>
                {
                    b.Property<int>("NumeroPedido");

                    b.Property<DateTime>("DataVenda");

                    b.Property<int>("ProdutoId");

                    b.Property<int>("QTDVendida");

                    b.Property<decimal>("Valor");

                    b.HasKey("NumeroPedido", "DataVenda", "ProdutoId");

                    b.HasAlternateKey("DataVenda", "NumeroPedido", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Produtos_Pedidos");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.ItensCarrinhoCompra", b =>
                {
                    b.Property<int>("ItemCarrinhoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrinhoCompraId")
                        .HasMaxLength(200);

                    b.Property<int?>("ProdutoId");

                    b.Property<int>("Quantidade");

                    b.HasKey("ItemCarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensCarrinhoCompras");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.Pedido", b =>
                {
                    b.Property<int>("NumeroPedido");

                    b.Property<DateTime>("DataVenda");

                    b.Property<string>("CarrinhoCompraId")
                        .HasMaxLength(100);

                    b.Property<int>("ClienteId");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("NumeroPedido", "DataVenda");

                    b.HasAlternateKey("DataVenda", "NumeroPedido");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId");

                    b.Property<string>("DescricaoCurta")
                        .HasMaxLength(50);

                    b.Property<string>("DescricaoDetalhada")
                        .HasMaxLength(200);

                    b.Property<string>("Fabricante")
                        .HasMaxLength(50);

                    b.Property<string>("ImagemProduto")
                        .HasMaxLength(200);

                    b.Property<decimal>("Peso");

                    b.Property<decimal>("Preco");

                    b.Property<DateTime>("Validade");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.TipoPagamento", b =>
                {
                    b.Property<int>("TipoPagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Parcelado")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("QtdParcelas")
                        .HasMaxLength(1);

                    b.Property<decimal>("ValorMinimo");

                    b.HasKey("TipoPagamentoId");

                    b.ToTable("TiposPagamentos");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.Usuario", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Role");

                    b.Property<string>("Status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.IntercPagamentoPedido", b =>
                {
                    b.HasOne("Sistema_PetShop.Models.TipoPagamento", "TipoPagamento")
                        .WithMany("PagamentoPedidos")
                        .HasForeignKey("TipoPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sistema_PetShop.Models.Pedido", "Pedidos")
                        .WithMany("PagamentoNotas")
                        .HasForeignKey("NumeroPedido", "DataVenda")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema_PetShop.Models.IntercProdutoPedido", b =>
                {
                    b.HasOne("Sistema_PetShop.Models.Produto", "Produto")
                        .WithMany("ItensProdutoPedidos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Sistema_PetShop.Models.Pedido", "Pedidos")
                        .WithMany("ItensProdutoNotas")
                        .HasForeignKey("NumeroPedido", "DataVenda")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema_PetShop.Models.ItensCarrinhoCompra", b =>
                {
                    b.HasOne("Sistema_PetShop.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("Sistema_PetShop.Models.Pedido", b =>
                {
                    b.HasOne("Sistema_PetShop.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Sistema_PetShop.Models.Produto", b =>
                {
                    b.HasOne("Sistema_PetShop.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
